sudo: false

language: node_js

node_js:
  - node

branches:
  only:
    - dev
    - master

install:
  - npm install

script:
  - npm run prettier

deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"
  on:
    branch: dev